version: "3.9"

services:

  webapp:
    image: alexrazek/test-2:version-1
    command: gunicorn app:app -b 0.0.0.0:5000
    restart: always

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always